on:
  push:
    tags:
      - "*"

name: Release

permissions:
  contents: write
  packages: write
  # issues: write
  # id-token: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      
      - id: token-up
        name: Get GH App Token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.JIRA_CLI_ACTIONS_APP_ID }}
          private-key: ${{ secrets.JIRA_CLI_ACTIONS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: |
            jira-cli
            homebrew-jira-cli
      
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: "~> v1"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ steps.token-up.outputs.token }}
          # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
          # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
